[unstable]
build-std = ["std", "panic_abort"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "debuginfo=0",
    "-Clink-arg=-Wl,--gc-sections",
    "-Clink-arg=-Wl,--icf=all",
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Cllvm-args=--inline-threshold=45",
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-C", "debuginfo=0",
    "-Clink-arg=-Wl,--gc-sections",
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Cllvm-args=--inline-threshold=45",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "debuginfo=0",
    "-Clink-arg=-dead_strip",
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Cllvm-args=--inline-threshold=45",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "debuginfo=0",
    "-Clink-arg=-dead_strip",
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Cllvm-args=--inline-threshold=45",
]
